### ISSUE TITLE
mac os run ????

### ISSUE THREAD

**Issue by pullghjunkkk** [bahaabdelwahed/st#1]
paulchikkkk@f5c7de ~ % cd st
paulchikkkk@f5c7de st % python3 smartthings.py
Traceback (most recent call last):
  File "/Users/paulchikkkk/st/smartthings.py", line 6, in <module>
    from main import iot
  File "/Users/paulchikkkk/st/main.py", line 3, in <module>
    import pymongo
ModuleNotFoundError: No module named 'pymongo'
paulchikkkk@f5c7de st %

**Comment by bahaabdelwahed** [comment]
You need To install pymongo library to work with MongoDB https://pymongo.readthedocs.io/en/stable/installation.html

**Comment by pullghjunkkk** [comment]
paulchikkkk@f5c7de ~ % python3 -m pip install pymongo
DEPRECATION: Loading egg at /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/apkleaks-2.6.1-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wifi_password-1.1.1-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/Afuzz-0.1.12-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/MacMaster_Advanced_Network_Interface_Management_and_Monitoring-1.3.0-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
Collecting pymongo
  Downloading pymongo-4.8.0-cp311-cp311-macosx_10_9_x86_64.whl.metadata (22 kB)
Collecting dnspython<3.0.0,>=1.16.0 (from pymongo)
  Downloading dnspython-2.6.1-py3-none-any.whl.metadata (5.8 kB)
Downloading pymongo-4.8.0-cp311-cp311-macosx_10_9_x86_64.whl (645 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 645.6/645.6 kB 9.6 MB/s eta 0:00:00
Downloading dnspython-2.6.1-py3-none-any.whl (307 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 307.7/307.7 kB 9.3 MB/s eta 0:00:00
Installing collected packages: dnspython, pymongo
Successfully installed dnspython-2.6.1 pymongo-4.8.0

[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: python3 -m pip install --upgrade pip
paulchikkkk@f5c7de ~ % python3 -m pip install --upgrade pip
DEPRECATION: Loading egg at /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/apkleaks-2.6.1-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wifi_password-1.1.1-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/Afuzz-0.1.12-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/MacMaster_Advanced_Network_Interface_Management_and_Monitoring-1.3.0-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
Requirement already satisfied: pip in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (24.0)
Collecting pip
  Using cached pip-24.1.2-py3-none-any.whl.metadata (3.6 kB)
Using cached pip-24.1.2-py3-none-any.whl (1.8 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 24.0
    Uninstalling pip-24.0:
ERROR: Could not install packages due to an OSError: Cannot move the non-empty directory '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip-24.0.dist-info/': Lacking write permission to '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip-24.0.dist-info/'.


[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: python3 -m pip install --upgrade pip
paulchikkkk@f5c7de ~ % python3 -m pip install --upgrade pymongo
DEPRECATION: Loading egg at /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/apkleaks-2.6.1-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wifi_password-1.1.1-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/Afuzz-0.1.12-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/MacMaster_Advanced_Network_Interface_Management_and_Monitoring-1.3.0-py3.11.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
Requirement already satisfied: pymongo in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (4.8.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pymongo) (2.6.1)

[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: python3 -m pip install --upgrade pip
paulchikkkk@f5c7de ~ % cd st
paulchikkkk@f5c7de st % python3 smartthings.py
Traceback (most recent call last):
  File "/Users/paulchikkkk/st/smartthings.py", line 6, in <module>
    from main import iot
  File "/Users/paulchikkkk/st/main.py", line 9, in <module>
    import pyxploitdb
ModuleNotFoundError: No module named 'pyxploitdb'
paulchikkkk@f5c7de st % python3 smarthings.py -s --type TPLINK
/Library/Frameworks/Python.framework/Versions/3.11/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/paulchikkkk/st/smarthings.py': [Errno 2] No such file or directory
paulchikkkk@f5c7de st %

**Comment by bahaabdelwahed** [comment]
Please consider running setup.sh to install all requirement or do it manually
the error show that pyxploitdb Library is not installed https://pypi.org/project/pyxploitdb/
